workflows:
  ios:
    name: iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: development  
        bundle_identifier: com.yourcompany.opennutritracker
        automatic_signing: true        
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS IPA
        script: |
          flutter build ipa --debug --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
